### ISSUE TITLE
download page 구조 개편 및 합치기

### ISSUE THREAD

**Issue by ananjaemin** [ananjaemin/tempfiles-frontend#24]
- [ ] download page 이동 custom hook 제작없음 - 취소
- [x] upload, filelist 했을때 다운로드 페이지 통일

**Comment by ananjaemin** [comment]
1. upload 할때 expires 업로드된 날짜가 1-1-1로 고정임
2. upload 할때 받는 name, size는 앞이 소문자인데 filelist에서는 Name, Size로  대문자라서 문제가 됨
 - 대문자면 좋겠음

**Comment by minpeter** [comment]
1. 아직 파일 만료 기능이 구현되지 않음
추후 구현 예정
2. 바로 대문자로 변경하겠음
