### ISSUE TITLE
api page 개발

### ISSUE THREAD

**Issue by minpeter** [ananjaemin/tempfiles-frontend#4]
api 페이지를 개발해보자

**Comment by minpeter** [comment]
@ananjaemin 부탁할께... 너가 이어서 해줘
https://tfb.minpeter.cf/info
에서 백엔드 사용법 정리해뒀어

**Comment by minpeter** [comment]
![image](https://user-images.githubusercontent.com/62207008/198926695-eabea514-c18e-4506-9739-51d3d5d5fd1d.png)

**Comment by minpeter** [comment]
## 디자인 수정
![Uploading image.png…]()

**Comment by ananjaemin** [comment]
제거 완료 
- 현재 api Info가 4개 밖에 없어서 스크롤은 작동안됨
