### ISSUE TITLE
백엔드 url 변동

### ISSUE THREAD

**Issue by minpeter** [ananjaemin/tempfiles-frontend#53]
- [x]  lastModifed -> uploadDate
- [x] /list를 파일 목록만 조회하는 /list와 파일 세부사항을 조회하는 /file/:id/:filename으로 분리함

**Comment by ananjaemin** [comment]
- [ ] checkpw 전체 페이지 개편

**Comment by ananjaemin** [comment]
1. 파일이름이 한국어 이거나 스페이스(띄어쓰기)가 들어가면 문제가 생김
   - url로 전송하다보니 인코딩 디코딩 에서 문제가 생긴걸로 보임
   - 로그상으로 봤을때 url 디코딩이 안된걸로 추정
   
![image](https://user-images.githubusercontent.com/81001494/201308788-82d82490-b800-44dd-997d-35df8c29d351.png)
@minpeter

**Comment by ananjaemin** [comment]
그 외 스페이스바가 없는 영어는 잘된다.

**Comment by ananjaemin** [comment]
업로드는 디코딩이 잘된걸로 추정
단. file api가 디코딩이 안되는걸로 추정됨

**Comment by ananjaemin** [comment]
![image](https://user-images.githubusercontent.com/81001494/201309899-b2693b3a-1d9c-4cf8-9c2b-3959a120b050.png)
다운로드 할때 파일명이 디코딩이 안된상태로 된다.

**Comment by ananjaemin** [comment]
이유는 모르나 파일 삭제가 가끔씩 500이 뜬다.

**Comment by minpeter** [comment]
와 버그 모음집이다

**Comment by minpeter** [comment]
버그 모음집 컷!
