### ISSUE TITLE
kubernetes 클러스터 배포를 위해 dockerizing

### ISSUE THREAD

**Issue by minpeter** [ananjaemin/tempfiles-frontend#54]
최종적으로 클라이언트도 스케일링 할껀데 우선 도커 이미지가 필요해요!!

**Comment by ananjaemin** [comment]
우리 favicon도 잊지마요~~

**Comment by minpeter** [comment]
파비콘은 당연히 기억하고 있죠 ㅎ

**Comment by minpeter** [comment]
![image](https://user-images.githubusercontent.com/62207008/201359034-81581a11-d682-4fc3-beab-86ae96833a9d.png)
아이콘을 그대로 사용하는 ㅎ
